config/routes.rb
Bills::Application.routes.draw do
  devise_for :users
  resources :payment_methods, :path => '/payment-methods'
  get "home/index"
  root 'home#index'
  resources :payments
  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :payments
  belongs_to :user

  validates :name, presence: true, length: { minimum: 2 }

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :company
  belongs_to :payment_method

  validates :company_id, presence: true
  validates :payment_method_id, presence: true
  validates :amount, presence: true
  validates :date, presence: true
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_many :payments
  belongs_to :user

  validates :name, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :companies
  has_many :payments, through: :companies
  has_many :payment_methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = current_user.companies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies = current_user.companies
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = current_user.payment_methods
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = current_user.payment_methods.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment_method }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = current_user.payment_methods.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:name, :description)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = current_user.payments.order('date desc')
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = current_user.payments.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = current_user.payments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:company_id, :amount, :payment_method_id, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def table_helper(header = '', sub_header = '', columns = [], &block)
    table = ''
    table << "<div class='panel panel-primary'>"
    table << "<div class='panel-heading'><strong>#{header}</strong></div>"
    table << "<div class='panel-body'><p>#{sub_header}</p></div>" unless sub_header.empty?
    table << "<table class='table'><thead><tr>"

    columns.each do |column|
      table << "<th>#{column}</th>"
    end

    table << capture(&block) if block_given?

    table << "</tr>"
    table << "</thead>"
    table << "<tbody>"

    table << "</body>"
    table << "</table>"
    table << "</div>"
    table << "</div>"
    table << "</div>"
    table
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>

        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <div class="alert alert-danger" role="alert">
              <h4><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h4>

              <ul>
                <% @company.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>

    <% end %>

    <div class="input-group">
      <%= f.text_field :name, :class => 'form-control', :placeholder => 'Company Name' %>
    </div>

    <br/>

    <div class="input-group">
      <%= f.text_area :description, size: "60x12", :class => 'form-control', :placeholder => 'Description' %>
    </div>

    <br/>
    <div class="actions">
      <%= f.submit :class => 'btn btn-default' %>
    </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div> <%= link_to 'New Company', new_company_path, :class => 'btn btn-primary' %> </div>

<br />

<%== table_helper('Companies', '', ['Name', 'Desc', 'Created at', 'Updated at', '', '', '']) do %>
  <div/> <!-- hack to prevent empty block -->
    <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.description %></td>
          <td><%= company.created_at.to_s %></td>
          <td><%= company.updated_at.to_s %></td>
          <td><%= link_to 'Show', company, :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_company_path(company), :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', company, :class => 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <% end %>
<% end %>

app/views/companies/new.html.erb
<h1>Add a company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @company.name %></h3>
  </div>
  <div class="panel-body">
    <%= @company.description %>
  </div>
  <div class="panel-footer">
    <%= @company.created_at %>
  </div>
</div>

<br />

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/home/index.html.erb
<%= render 'shared/graph' %>

<div class="jumbotron">
  <div class="container">
    <h1>Hello, world!</h1>
    <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <p><a class="btn btn-primary btn-lg">Learn more</a></p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert alert-success" role="alert"><%= alert %></div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Bill Pay</a>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li <% if params[:controller] == 'home' %>class='active'<% end %>><a href='<%= root_path %>'>Home</a></li>
        <li <% if params[:controller] == 'payments' %>class='active'<% end %> ><a href="<%= payments_path %>">Payments</a></li>
        <li <% if params[:controller] == 'companies' %>class='active'<% end %> ><a href="<%= companies_path %>">Companies</a></li>
        <li <% if params[:controller] == 'payment_methods' %>class='active'<% end %> ><a href="<%= payment_methods_path %>">Payment Methods</a></li>
        <li>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bills</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
</head>
<body>
<% if current_user %>
  <%= render partial: 'layouts/nav' %>
<% end %>


<% if notice or alert %>
  <%= render partial: 'layouts/flash_messages' %>
<% end %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10"><%= yield %></div>
  <div class="col-md-1"></div>
</div>


</body>
</html>

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method) do |f| %>
    <% if @payment_method.errors.any? %>
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <div class="alert alert-danger" role="alert">
              <h4><%= pluralize(@payment_method.errors.count, "error") %> prohibited this company from being saved:</h4>

              <ul>
                <% @payment_method.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
    <% end %>

    <div class="input-group">
      <%= f.text_field :name, :class => 'form-control', :placeholder => 'Payment method name' %>
    </div>

    <br/>

    <div class="input-group">
      <%= f.text_area :description, size: "60x12", :class => 'form-control', :placeholder => 'Description' %>
    </div>

    <br/>

    <div class="actions">
      <%= f.submit :class => 'btn btn-default' %>
    </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Made</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<div> <%= link_to 'New Payment method', new_payment_method_path, :class => 'btn btn-primary' %> </div>

<br />

<%== table_helper 'Payment Methods', 'Checking account, credit cards, debit cards, etc.', ['Name', 'Desc', 'Created at', 'Updated at', '', '', ''] do %>
  <div/> <!-- hack to prevent empty block -->
    <% @payment_methods.each do |payment_method| %>
        <tr>
          <td><%= payment_method.name %></td>
          <td><%= payment_method.description %></td>
          <td><%= payment_method.created_at %></td>
          <td><%= payment_method.updated_at %></td>
          <td><%= link_to 'Show', payment_method, :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_payment_method_path(payment_method), :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', payment_method, :class => 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
<% end %>

app/views/payment_methods/new.html.erb
<h1>Add payment method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_method.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment_method.description %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
    <% if @payment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

          <ul>
            <% @payment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <label for='payment[company_id]'>Company:</label>
      <%= collection_select(:payment, :company_id, Company.all, :id, :name) %>
    </div>

    <div>
      <label for='payment[payment_method_id]'>Payment method:</label>
      <%= collection_select(:payment, :payment_method_id, PaymentMethod.all, :id, :name) %>
    </div>

    <div class="input-group">
      <%= f.text_field :amount, :class => 'form-control', :placeholder => 'Amount' %>
    </div>

    <div class="input-group">
      <%= f.text_field :date, :class => 'form-control', :placeholder => 'Date' %>
    </div>

    <br/>
    <div class="actions">
      <%= f.submit :class => 'btn btn-default' %>
    </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div> <%= link_to 'New Payment', new_payment_path, :class => 'btn btn-primary' %> </div>

<br />

<%== table_helper 'Payments', 'List of payments', ['Company', 'Amount', 'Date', '', '', ''] do %>
  <div/> <!-- hack to prevent empty block -->
    <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.company.name.to_s %></td>
          <td><%= payment.amount.to_s %></td>
          <td><%= payment.date.to_s %></td>
          <td><%= link_to 'Show', payment, :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_payment_path(payment), :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', payment, :class => 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
<% end %>

app/views/payments/new.html.erb
<h1>Add a new payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @payment.company.name %></h3>
  </div>
  <div class="panel-body">
    $<%= @payment.amount.to_f %>
  </div>
  <div class="panel-footer">
    <%= @payment.date %>
  </div>
</div>

<br />

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/shared/_graph.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>

<div id="container" style="width:100%; height:400px;"></div>

<script>
    $(function () {
        $('#container').highcharts({
            chart: {
                type: 'line'
            },
            title: {
                text: 'Payments'
            },
            xAxis: {
                type: 'datetime',
                dateTimeLabelFormats: {
                    month: '%y-%b ',
                }
            },
            yAxis: {
                title: {
                    text: 'Bill amount'
                }
            },
            series: [
                // data: [[5, 2], [6, 3], [8, 2]]
                <% @companies.each do |company| %>
                {
                    name: '<%= company.name %>',
                    data: [
                        <% company.payments.each do |payment| %>
                        [
                            <%= payment.amount.to_s %>
                        ],
                        <% end %>
                    ]
                } ,
                <% end %>

            ]
        });
    });
</script>